version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: "sphinx-rtd-theme"
    versions: ["0.5.0"]
  open-pull-requests-limit: 10
  reviewers:
  - mondeja
  assignees:
  - mondeja
