version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  ignored_updates:
  - match:
    dependency_name: "sphinx-rtd-theme"
    version_requirement: 0.5.0
  open-pull-requests-limit: 10
  reviewers:
  - mondeja
  assignees:
  - mondeja
