language: python
os: linux
dist: focal
cache: false
install:
  - travis_retry pip install -U pip virtualenv
  - wget https://github.com/mity/md4c/archive/release-0.4.4.tar.gz
  - tar -zxvf release-0.4.4.tar.gz
  - rm release-0.4.4.tar.gz
  - cd md4c-release-0.4.4
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  - python -m virtualenv venv
  - . venv/bin/activate && python -m pip install -e git+https://github.com/dominickpastore/pymd4c.git@master#egg=md4c && python -m pip install -e git+https://github.com/mondeja/md2po.git@master#egg=md2po && python -m pip install pytest
matrix:
  include:
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: bionic
      before_script:
        - pip install pytest-cov coveralls
      script: pytest --cov=mdpo --cov-config=setup.cfg
      after_success:
        - coveralls
    - python: 3.8
      dist: focal
      before_script:
        - pip install flake8
      script: flake8 test mdpo docs setup.py
    - python: 3.7
      dist: focal
script: . venv/bin/activate && python -m pytest -svv
